### ISSUE TITLE
'editions' is an undeclared required dependency, resulting in fatal failure when running CSON CLI without previously-installed (globally or locally) 'editions' package

### ISSUE THREAD

**Issue by danielweck** [bevry/cson#132]
https://github.com/bevry/cson/blob/1e48f2184d27664dadbb7b790d0cf2dd03fcfea1/package.json#L105-L111

https://github.com/bevry/cson/blob/1e48f2184d27664dadbb7b790d0cf2dd03fcfea1/bin/cson2json#L4

My current workaround is to explicitly `npm install editions --save-dev`, which modifies my project's own `package.json`. This workaround should not be needed, as in practice `editions` really is a *required* dependency of the CSON package itself (and therefore a transitive dependency for my project, not a direct one).

**Comment by balupton** [comment]
Thanks, will fix in the next 24 hours

**Comment by danielweck** [comment]
Thanks :)

**Comment by balupton** [comment]
Fixed in v6.9.0 which is [being published now](https://travis-ci.com/bevry/cson/builds/141445180)
