### ISSUE TITLE
Option to produce source maps (src-dest line mapping)

### ISSUE THREAD

**Issue by Zearin** [bevry/cson#29]
Since one of CSON’s main selling points is that of a readable alternative to JSON, many people will be writing in CSON, and converting to JSON for use with other code.  If something happens in that generated code, it’s desirable to have some way to find where the JSON’s relevant counterpart is in the CSON.

I know that JSON doesn’t actually allow comments.  Maybe…

- an option to output a line-mapping from CSON ► JSON
- offer event hooks for people to customize however they like
- …?

**Comment by Zearin** [comment]
So, CSON 2.0 is out!  And its parser has been abstracted to groupon/cson-parser.  Yay!

I’m rusty on the code for this.  Does anyone know if it’s possible to get source maps of the original CSON to the generated JSON?  (Maybe the refactoring of groupon/cson-parser made it easier…?)

**Comment by balupton** [comment]
This is now an issue for groupon/cson-parser rather than for us. When they add sourcemap support to their cson parser, we'll add support for their API in bevry/cson.
