### ISSUE TITLE
Provide a static (non-turing) parser of CSON

### ISSUE THREAD

**Issue by balupton** [bevry/cson#33]
As the current parser executes CoffeeScript code (albeit in a node virtual machine), and considering atom.io's use case of CSON, which is leading to more widespread interest than the original developers writing configuration to be executed on their own machines, it could make sense for some efforts to go into writing a static (non-turing) parser of CSON for the purpose of safe execution, opening CSON up to be used in untrusted environments #32

Personally I have no need for such things, as it is outside of my use-case for CSON, however I would happily facilitate and help out in any way I can with such an initiative.

**Comment by balupton** [comment]
Hey everyone, v2 of CSON will be out soon (see it on the "safety-rewrite") branch, which will use cson-safe. Still really dislike the name cson-safe, I wish it was cson-static instead :-( but oh well.

Really excited to get this release out, great work to the cson-safe team! Huge props. I'll send a pull request to your readme with some updated wording (as we will now be using your project) as well as update our readme to link to you.

**Comment by jkrems** [comment]
Great to hear! Will see that we get a rename going (e.g. to `cson-parser`). I agree that name will be confusing once the two projects share the same guts.

**Comment by jkrems** [comment]
Renamed to `cson-parser`: https://www.npmjs.com/package/cson-parser

**Comment by balupton** [comment]
:+1:

**Comment by balupton** [comment]
Fixed in v2

**Comment by balupton** [comment]
@jkrems how did you get npm to rename `cson-safe` to `cson-parser`?

**Comment by jkrems** [comment]
@balupton By cheating, basically. I changed the name in package.json and then released one last "fake" version of the old package that just contained a README change (https://github.com/groupon/cson-parser/commit/d96425538818889cbb2e573a3548af099a090801). Unfortunately I don't think npm supports renames properly.
