### ISSUE TITLE
Arrays of Object Literals

### ISSUE THREAD

**Issue by TobiasRaeder** [bevry/cson#37]
It seems to me there is an issue with the parser, but maybe it is my fault, not 100% sure.

If I try to parse 
[
  name: 'something'
  attribute: 'foo'
,
  name: 'somethign else'
  attribute: 'bar'
]

using cson it complains about an unexpected , (use to denote the new object)

try coffeescript on coffeescript.org parses it just fine though,
which is why I figured it should work in cson too.

Any hints would be great.

**Comment by balupton** [comment]
Issue for cson-parser package
