### ISSUE TITLE
json2cson outputs unsafe cson

### ISSUE THREAD

**Issue by creynders** [bevry/cson#41]
Hi there,

I'm looking for the fastest way to get json converted to cson that is parseable by cson-safe. Problem is that AFAIK the cson module outputs unsafe cson, i.e. surrounded with brackets and it appears to me that cson-safe and atom-season only provide parsing of cson, right?
I noticed that [the brackets are being added in the stringifySync method](https://github.com/bevry/cson/blob/master/src/lib/cson.coffee#L162), would it be possible to drop this? Or maybe check for a `--safe` flag or something?

I don't mind getting my hands dirty so if you don't have the time, but could tell me what direction you want to take I'm more than willing to do the changes myself.

**Comment by balupton** [comment]
Fixed in v2
