### ISSUE TITLE
Allow .cson suffix-free files to be parsed

### ISSUE THREAD

**Issue by gvn** [bevry/cson#43]
I'm trying to use CSON for a config file I'm naming `.bzrc`.

I'm using `parseFileSync` and getting this error:

``` bash
[Error: CSON.parseFileSync: Unknown extension type for /Users/gsuntop/.bzrc]
```

Renaming to `.bzrc.cson` works as expected, but I'd prefer not to use this suffix. Can non-suffixed files be allowed to work? Thanks!

**Comment by balupton** [comment]
Can someone send a pull request for this and I'll review.

**Comment by balupton** [comment]
Closing due to lack of initiative on this issue showing a lack of value for this issue
