### ISSUE TITLE
CSON vs YAML or why CSON ?

### ISSUE THREAD

**Issue by GammaNu** [bevry/cson#51]
json is full of ,{}[]"" that bother me and probably you.
yaml is more human readable
cson look to reach the same goal than yaml.

So, what are the différences ?
- yaml references system `&anchor content *anchor #as reference`
- space and - are allowed in key without bracket in yaml
- the array/map syntaxe differenciation is not the same in yaml and cson

What cson have that yaml don't have ?
- simplicity (less advensed feature you don't want to learn and implement in your parser) ?
- efficiency (faster to parse)

Anything else ?

**Comment by mcandre** [comment]
+1 lol
