### ISSUE TITLE
`CSON.parseFile` returns `undefined` on Node.JS 0.11.* and io.js '1.0.*'

### ISSUE THREAD

**Issue by jacobbubu** [bevry/cson#53]
As the subject.

**Comment by pheuter** [comment]
Same.

**Comment by jacobbubu** [comment]
looks like this is a coffee-script bug on new V8 engine. https://github.com/jashkenas/coffeescript/issues/3810

**Comment by balupton** [comment]
Looking into it.

**Comment by balupton** [comment]
Fixed in v2

**Comment by rambo-panda** [comment]
Why delete `parseFileSync` method?

**Comment by balupton** [comment]
@rambo-panda all are sync now, callbacks are optional
