### ISSUE TITLE
js2coffee v2.0.0 is out

### ISSUE THREAD

**Issue by rstacruz** [bevry/cson#55]
cson depends on js2coffee 0.3.x. Here are some notes on migrating to 2.x: https://github.com/js2coffee/js2coffee/blob/master/notes/Migration_guide.md

**Comment by balupton** [comment]
Thanks @rstacruz, v2.0.0 of CSON will actually use `cson-safe` for stringifying so won't be using js2coffee anymore (despite how awesome it is).

I do wonder though, any idea how to turn a javascript object in memory that also contains functions into a text format such that it can be converted by js2coffee into coffeescript text?

**Comment by rstacruz** [comment]
lol. no idea—you'll probably need write your own `stringify(object)` function! but then again, marshaling a function using Function.prototype.toString() is probably not such a good idea :)
