### ISSUE TITLE
Is CSON a superset of JSON?

### ISSUE THREAD

**Issue by tomekwi** [bevry/cson#58]
It looks like it anyway:

``` sh
curl https://raw.githubusercontent.com/bevry/cson/master/package.json | cson2json
```

How about explicitly mentioning that in the spec? [Like YAML does](http://www.yaml.org/spec/1.2/spec.html#id2759572).

**Why:** A library I’m developing should accept JSON and CSON configuration files. Determining whether a file is JSON or CSON can be tedious. I’d like to keep it simple, and just always parse the config with CSON.

**Comment by tomekwi** [comment]
Maybe, just maybe, we could also define CSON as a subset of YAML? It looks like it at first sight, though I’m sure there are edge cases.

**Comment by balupton** [comment]
> A library I’m developing should accept JSON and CSON configuration files. Determining whether a file is JSON or CSON can be tedious. I’d like to keep it simple, and just always parse the config with CSON.

This CSON package should make that easy via `parseFile` and `parseString`. Passing a `filename` option will autodetect what it should be.

> How about explicitly mentioning that in the spec? Like YAML does.

Good idea. CSON is a superset of JSON.

> Maybe, just maybe, we could also define CSON as a subset of YAML?

CSON is not compatible with YAML. Multiline strings are handled differently from my understanding.

**Comment by tomekwi** [comment]
> Passing a filename option will autodetect what it should be.

Does that mean that `cson2json` does the same?

**Comment by dgreensp** [comment]
Does CSON have different indentation rules than CoffeeScript?

Taking whitespace into account, this JSON is not valid CoffeeScript:

```
{"a":
{"b":1}}
```

Therefore, CoffeeScript is not a superset of JSON.

**Comment by tomekwi** [comment]
I guess that’s what @jkrems meant by

> I'd add an "(*) well-formatted JSON".

**Comment by JonasT** [comment]
Did you ever consider not allowing `{ ... }` and other JSON notation? It's ugly, it's unnecessary (there are infinite JSON parsers after all which make a transition of old data trivial) and it only makes the specs more complicated for features people aren't going to use anyway (who wants to write things in uglier syntax on purpose?).

**Comment by balupton** [comment]
Discussion for this should be over at https://www.npmjs.com/package/cson-parser
