### ISSUE TITLE
Regex support ?

### ISSUE THREAD

**Issue by artemisart** [bevry/cson#62]
It would be nice to add support for /regex/ and ///block regex///

**Comment by guyskk** [comment]
Since JSON is not support Regex, I think it's better to stay the same with JSON. For language independent and  ideal data-interchange language.

> JSON is a text format that is completely language independent but uses conventions that are familiar to programmers of the C-family of languages, including C, C++, C#, Java, JavaScript, Perl, Python, and many others. These properties make JSON an ideal data-interchange language.

**Comment by balupton** [comment]
Will be an issue for https://www.npmjs.com/package/cson-parser
