### ISSUE TITLE
add a paragraph with known implementations in other languages (idea)

### ISSUE THREAD

**Issue by jabbalaci** [bevry/cson#63]
Hi,

It'd be useful to add a list of known implementations in other languages (like at the bottom of http://json.org/ ). For instance, I'd like to use CSON in Python. Which library is suggested?

Also, there is another CSON called Cursive Script Object Notation (https://github.com/lifthrasiir/cson). It's a pity they have the same name, it's confusing.

Best,

Laszlo

**Comment by balupton** [comment]
Great idea. Want to send over a pull request?

**Comment by balupton** [comment]
Closing due to due showing a lack of interest/initiative to value this
