### ISSUE TITLE
typechecker.js throw error on require CSON

### ISSUE THREAD

**Issue by GrimDev** [bevry/cson#64]
Hi.

I use cson 3.1.0 and the following error is thrown on "require "cson".

```
/node_modules/cson/node_modules/extract-opts/node_modules/typechecker/es6/lib/typechecker.js:29
for ( let type of types ) {
            ^^^^^
```

But the library works properly after that.

Do you know what does it mean ?

**Comment by balupton** [comment]
Which version of node are you using?

**Comment by GrimDev** [comment]
I was using nodev0.10.29 of 2014-05 O_o.

It was on a local repository never updated.

No problems now on 4.0.0 :)

Thx

**Comment by kvz** [comment]
Running into the same thing here on `v0.10.24`. Is a newer node required for cson?

If so, would it make sense to reflect that in: https://github.com/bevry/cson/blob/master/package.json#L67?

**Comment by balupton** [comment]
It's just a warning, it can be ignored.

**Comment by kvz** [comment]
It turns out there was another issue that caused a fatality over here. The warning made it appear it originated from typechecker, tracing back to cson. All good here now.
