### ISSUE TITLE
Outputting a literal character

### ISSUE THREAD

**Issue by stramel** [bevry/cson#66]
I have a string that contains literal characters that are being converted when writing to a file. Is there anyway to output the actual character? I have `\t` that I have to be output in the string.

**Comment by stramel** [comment]
@balupton Any thoughts?

**Comment by balupton** [comment]
@stramel may be an issue for https://github.com/groupon/cson-parser

**Comment by stramel** [comment]
@balupton It looks like it was resolved as of v1.0.9 in groupon/cson-parser. Any chance you would be willing to update and release a new version? I could also do a PR if you don't have time.

**Comment by balupton** [comment]
@stramel no update is needed, just a reinstall or `npm cache clean cson-parser` then install
