### ISSUE TITLE
source map support is broken the first time cson.requireFile is called

### ISSUE THREAD

**Issue by vincentcr** [bevry/cson#70]
using 3.0.2

if i throw an error before calling cson.requireFile, i get the source-mapped stack trace. 
if i throw an error after calling cson.requireFile, i see the compiled stack trace without source mappings.

**Comment by balupton** [comment]
Could you provide a complete test case for reproducing the two cases above

**Comment by balupton** [comment]
This seems like it just needs better error handling which would be accomplished by a promise rewrite #88

**Comment by lenovouser** [comment]
I am also experiencing this, is there something I can do on my side to fix this temporarily in my project?

**Comment by balupton** [comment]
If you are just using .cson then try using the underlying safe cson parser by groupon directly
