### ISSUE TITLE
parseCSONString passes JSON

### ISSUE THREAD

**Issue by idleberg** [bevry/cson#71]
I noticed that `parseCSONString` will accept passed JSON

    CSON.parseCSONString({"JSON": "not CSON"})

I'd expect this to throw an error, otherwise what would be the difference between `parseString` and `parseCSONString`?

**Comment by balupton** [comment]
JSON is valid CSON

**Comment by balupton** [comment]
Or is the issue more that it is not a string being passed in your code sample?

**Comment by idleberg** [comment]
I use your package for an [Atom](http://atom.io) plugin and since I don't want to rely on the scope alone (which Atom determines by file extension), I wanted to use `parseCSONString` to test whether I'm working with CSON or JSON.

**Comment by balupton** [comment]
Well, as JSON is a subset of CSON, it means JSON is valid CSON. However, CSON is not a subset of JSON, which means CSON is not valid CSON. Inverse your try catch and you'll be good.

**Comment by idleberg** [comment]
OK, thanks!
