### ISSUE TITLE
README doesn't link format specification

### ISSUE THREAD

**Issue by JonasT** [bevry/cson#77]
The README doesn't link a format specification (at least as far as I can see). Please add a link with a complete formal specification of the format comparable to https://tools.ietf.org/html/rfc7159 , preferably also an additional one with some neat easily understandable format e.g. like the flow graphs presented on http://www.json.org/ .

I assume people who know CoffeeScript well can "guess" the format, but that's neither optimal nor is it gonna help others who think about adopting it.

**Comment by balupton** [comment]
Probably an issue for https://www.npmjs.com/package/cson-parser

**Comment by JonasT** [comment]
For what it's worth, I filed a ticket here: https://github.com/groupon/cson-parser/issues/61
