### ISSUE TITLE
Change dependency to CoffeeScirpt 2

### ISSUE THREAD

**Issue by kahogeoff** [bevry/cson#82]
Since CoffeeScript 2 was came out, this library with old dependency "coffee-script"(CoffeeScript 1.x) no longer work with the latest project.

So, the the dependency may need to upgrade to "coffeescript"(CoffeeScript 2.x) instead of "coffee-script"(CoffeeScript 1.x).

**Comment by balupton** [comment]
+1 - would love a PR

**Comment by bsott** [comment]
Maybe something like this  https://github.com/bevry/cson/pull/84 ?

**Comment by balupton** [comment]
closing, see https://github.com/bevry/cson/pull/84#issuecomment-360372308
