### ISSUE TITLE
Allow binary to handle whole directories

### ISSUE THREAD

**Issue by brettz9** [bevry/cson#85]
Hi,

I appreciate your work on this. While I'm normally more comfortable in the JavaScript world, CoffeeScript has a particularly strong appeal to me with hand-maintained JSON such as locale files.

I think it would be very handy if your binary could handle whole directories (even including subdirectories), with an output directory and file extension change.

Naturally, one could create one's own script to do this, but having it possible as one succinct line in `package.json` would be quite handy and ought to facilitate more use of cson.

Thanks!

**Comment by balupton** [comment]
Perhaps one of these already does it https://www.npmjs.org/browse/depended/cson-parser
