### ISSUE TITLE
Browserify CSON

### ISSUE THREAD

**Issue by templarundead** [bevry/cson#86]
I've made browserify version of cson with simple code

"use strict";
var CSON = require('cson')
var result = CSON.createCSONString({a:{b:'c'}}, {})
if ( result instanceof Error ) {
    console.log(result.stack)
} else {
    console.log(result)
};

But console throw: Error: Cannot find module '/..\node_modules\cson/package.json'

Any help?

**Comment by balupton** [comment]
CSON will not work on the web browser as it depends on a file system, you should use `cson-parser` instead.

**Comment by templarundead** [comment]
Thank you!
