### ISSUE TITLE
Editions error (no suitable editions for this environment) precede compilation error message

### ISSUE THREAD

**Issue by brutalcrozt** [bevry/cson#94]
![image](https://user-images.githubusercontent.com/3001652/66113684-768ac700-e5f7-11e9-81aa-18d0291020d9.png)

I was misunderstood the problem,
the main problem was syntax on my cson, but its reports like so.
Is it possible to hide these messages so the user can focus on compilation error messages?

**Comment by balupton** [comment]
try v6
